import {
  BarChart3,
  Building2,
  Car,
  CheckCircle,
  Clock,
  DollarSign,
  ImageIcon,
  Layers,
  Rocket,
  Share2,
  Shield,
  Shirt,
  ShoppingBag,
  Sparkles,
  TrendingUp,
  UserCheck,
  Users,
  Wand2,
  Zap,
} from 'lucide-react';

export const iconMap = {
  barChart3: BarChart3,
  building2: Building2,
  car: Car,
  checkCircle: CheckCircle,
  clock: Clock,
  dollarSign: DollarSign,
  image: ImageIcon,
  layers: Layers,
  rocket: Rocket,
  share2: Share2,
  shield: Shield,
  shirt: Shirt,
  shoppingBag: ShoppingBag,
  sparkles: Sparkles,
  trendingUp: TrendingUp,
  userCheck: UserCheck,
  users: Users,
  wand2: Wand2,
  zap: Zap,
};

export type IconName = keyof typeof iconMap;
